import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Helmet } from "react-helmet-async";
import { ArrowRight, Brain, Code, Cloud, Shield, Database, Monitor, Cpu } from "lucide-react";
import Layout from "@/components/layout/Layout";
import SectionHeader from "@/components/shared/SectionHeader";
import VideoHero from "@/components/shared/VideoHero";
import academiaVideo from "@/assets/videos/academia-hero.mp4";
import heroBg from "@/assets/hero-bg.jpg";

const roleTracks = [
  { icon: Brain, title: "AI Engineer", skills: "Python, TensorFlow, MLOps, NLP" },
  { icon: Cloud, title: "Cloud Architect", skills: "AWS, Azure, Kubernetes, IaC" },
  { icon: Shield, title: "SOC Analyst", skills: "SIEM, Threat Intel, Incident Response" },
  { icon: Code, title: "DevOps Engineer", skills: "CI/CD, Docker, Terraform, GitOps" },
  { icon: Monitor, title: "Full Stack Developer", skills: "React, Node.js, TypeScript, APIs" },
  { icon: Database, title: "Data Scientist", skills: "Statistics, ML, Python, SQL" },
  { icon: Cpu, title: "ERP Consultant", skills: "SAP, Oracle, Process Mapping" },
];

const alignmentSteps = [
  { num: "01", title: "Role Definition", desc: "Industry-aligned role specifications with real-time market data." },
  { num: "02", title: "Competency Benchmarking", desc: "Skills mapped against top-tier hiring standards globally." },
  { num: "03", title: "AI-Based Skill Gap Analysis", desc: "Personalized learning paths generated by AI assessment engines." },
  { num: "04", title: "Real-Time Performance Validation", desc: "Continuous evaluation through simulations and project-based assessment." },
];

const fadeInUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-80px" },
  transition: { duration: 0.5 },
};

const AcademiaPage = () => {
  return (
    <Layout>
      <Helmet>
        <title>Academia - Role-Ready Training | SOXIT</title>
        <meta name="description" content="SOXIT Academia engineers role-ready professionals through AI-driven competency mapping, skill gap analysis, and real-time performance validation." />
        <script type="application/ld+json">{JSON.stringify({
          "@context": "https://schema.org",
          "@type": "EducationalOrganization",
          "name": "SOXIT Academia",
          "description": "Career-focused skilling programs aligned to real industry demand.",
          "url": "https://soxit.in/academia"
        })}</script>
      </Helmet>

      <VideoHero
        videoSrc={academiaVideo}
        fallbackImage={heroBg}
        label="Academia"
        headline="Transforming Talent into Industry-Ready Professionals"
        subtext="Career-focused skilling programs aligned to real industry demand."
        ctaText="View Programs"
        ctaLink="#programs"
        overlayClass="bg-academia/70"
      />

      {/* Role Alignment Model */}
      <section id="programs" className="section-enterprise section-light">
        <SectionHeader label="Our Model" title="Role-to-Skill Mapping Engine" description="A systematic approach to bridging the gap between education and employment." />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
          {alignmentSteps.map((s, i) => (
            <motion.div key={s.num} {...fadeInUp} transition={{ ...fadeInUp.transition, delay: i * 0.1 }}>
              <div className="metric-card flex gap-5">
                <div className="text-2xl font-bold text-academia/30">{s.num}</div>
                <div>
                  <h3 className="font-bold text-foreground mb-1">{s.title}</h3>
                  <p className="text-sm text-muted-foreground">{s.desc}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Role Tracks */}
      <section className="section-enterprise section-sunken">
        <SectionHeader label="Role-Ready Tracks" title="Top Career Tracks" description="Each track is designed around actual hiring requirements from top-tier companies." />
        <div className="grid-enterprise max-w-7xl mx-auto">
          {roleTracks.map((r, i) => (
            <motion.div key={r.title} {...fadeInUp} transition={{ ...fadeInUp.transition, delay: i * 0.08 }}>
              <div className="metric-card">
                <div className="p-3 rounded-lg bg-academia/10 w-fit mb-4">
                  <r.icon size={24} className="text-academia" />
                </div>
                <h3 className="font-bold text-foreground mb-2">{r.title}</h3>
                <p className="text-xs text-muted-foreground font-mono">{r.skills}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* iSkill Platform */}
      <section className="section-enterprise section-dark">
        <SectionHeader label="Platform" title="iSkill — AI Learning Platform" description="Virtual labs, interview simulation, and predictive career mapping." light />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {[
            { title: "Virtual Labs", desc: "Hands-on cloud-based lab environments with real enterprise tools." },
            { title: "Interview Simulation", desc: "AI-powered mock interviews with role-specific technical scenarios." },
            { title: "Career Mapping", desc: "Predictive analytics for career trajectory and skill demand forecasting." },
          ].map((item, i) => (
            <motion.div key={item.title} {...fadeInUp} transition={{ ...fadeInUp.transition, delay: i * 0.1 }}>
              <div className="p-6 rounded-xl border border-surface-dark-foreground/10 hover:border-academia-accent/30 transition-colors">
                <h3 className="font-bold text-surface-dark-foreground mb-2">{item.title}</h3>
                <p className="text-sm text-surface-dark-foreground/60">{item.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTAs */}
      <section className="py-20 px-6 bg-academia">
        <motion.div {...fadeInUp} className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-academia-foreground mb-6">Start Your Journey</h2>
          <div className="flex flex-wrap justify-center gap-4">
            <Link to="/contact" className="inline-flex items-center gap-2 px-6 py-3 rounded-md bg-academia-accent text-academia-accent-foreground font-semibold text-sm hover:opacity-90 transition-opacity">
              Apply for Internship <ArrowRight size={16} />
            </Link>
            <Link to="/contact" className="inline-flex items-center gap-2 px-6 py-3 rounded-md border border-academia-foreground/30 text-academia-foreground font-semibold text-sm hover:bg-academia-foreground/10 transition-colors">
              Hire From Us <ArrowRight size={16} />
            </Link>
          </div>
        </motion.div>
      </section>
    </Layout>
  );
};

export default AcademiaPage;
