import { useState, useEffect } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { Helmet } from "react-helmet-async";
import { ArrowLeft, Upload, CheckCircle2, Loader2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";

type Job = Tables<"jobs">;

const applicationSchema = z.object({
  name: z.string().trim().min(2, "Name is required").max(100),
  email: z.string().trim().email("Invalid email").max(255),
  phone: z.string().trim().min(10, "Valid phone required").max(20),
  location: z.string().trim().min(2, "Location required").max(100),
  work_authorization: z.string().min(1, "Required"),
  experience: z.string().min(1, "Required"),
  relevant_experience: z.string().optional(),
  current_ctc: z.string().optional(),
  expected_ctc: z.string().optional(),
  notice_period: z.string().optional(),
  linkedin_url: z.string().url("Invalid URL").optional().or(z.literal("")),
  portfolio_url: z.string().url("Invalid URL").optional().or(z.literal("")),
  primary_skills: z.string().min(1, "At least one skill required"),
  secondary_skills: z.string().optional(),
  certifications: z.string().optional(),
  domain_exposure: z.string().optional(),
});

type ApplicationForm = z.infer<typeof applicationSchema>;

const steps = ["Basic Details", "Professional Details", "Skills", "Resume Upload"];

const JobApplication = () => {
  const { jobId } = useParams<{ jobId: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [job, setJob] = useState<Job | null>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [step, setStep] = useState(0);
  const [resumeFile, setResumeFile] = useState<File | null>(null);

  const form = useForm<ApplicationForm>({
    resolver: zodResolver(applicationSchema),
    defaultValues: { name: "", email: "", phone: "", location: "", work_authorization: "", experience: "", primary_skills: "" },
  });

  useEffect(() => {
    if (jobId) fetchJob();
  }, [jobId]);

  const fetchJob = async () => {
    const { data } = await supabase.from("jobs").select("*").ilike("job_post_id", jobId!.toUpperCase()).single();
    setJob(data);
    setLoading(false);
  };

  const onSubmit = async (values: ApplicationForm) => {
    if (!job) return;
    setSubmitting(true);

    try {
      let resume_url: string | null = null;

      // Upload resume if provided
      if (resumeFile) {
        const ext = resumeFile.name.split(".").pop();
        const path = `${job.job_post_id}/${Date.now()}-${values.email.replace(/[^a-z0-9]/gi, "_")}.${ext}`;
        const { error: uploadError } = await supabase.storage.from("resumes").upload(path, resumeFile);
        if (uploadError) throw uploadError;
        resume_url = path;
      }

      const { error } = await supabase.from("candidates").insert({
        candidate_profile_id: "", // auto-generated by trigger
        job_post_id: job.job_post_id,
        name: values.name,
        email: values.email,
        phone: values.phone,
        location: values.location,
        work_authorization: values.work_authorization,
        experience: values.experience,
        relevant_experience: values.relevant_experience || null,
        current_ctc: values.current_ctc || null,
        expected_ctc: values.expected_ctc || null,
        notice_period: values.notice_period || null,
        linkedin_url: values.linkedin_url || null,
        portfolio_url: values.portfolio_url || null,
        primary_skills: values.primary_skills.split(",").map((s) => s.trim()),
        secondary_skills: values.secondary_skills ? values.secondary_skills.split(",").map((s) => s.trim()) : null,
        certifications: values.certifications ? values.certifications.split(",").map((s) => s.trim()) : null,
        domain_exposure: values.domain_exposure || null,
        resume_url,
      });

      if (error) throw error;
      setSubmitted(true);
      toast({ title: "Application Submitted", description: "We'll review your application and get back to you." });
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Failed to submit application", variant: "destructive" });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <Layout><div className="pt-40 pb-20 text-center"><Loader2 className="animate-spin mx-auto text-consulting-accent" size={32} /></div></Layout>;
  if (!job || job.status !== "open") return (
    <Layout>
      <div className="pt-40 pb-20 px-6 text-center">
        <h1 className="text-2xl font-bold text-foreground">This position is no longer accepting applications</h1>
        <Link to="/careers" className="text-consulting-accent hover:underline mt-4 inline-block">← Back to Careers</Link>
      </div>
    </Layout>
  );

  if (submitted) return (
    <Layout>
      <Helmet><title>Application Submitted | SOXIT Careers</title></Helmet>
      <div className="pt-40 pb-20 px-6 text-center max-w-lg mx-auto">
        <motion.div initial={{ scale: 0.8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}>
          <CheckCircle2 size={64} className="mx-auto text-green-500 mb-6" />
          <h1 className="text-3xl font-bold text-foreground mb-3">Application Submitted!</h1>
          <p className="text-muted-foreground mb-2">Thank you for applying to <strong>{job.title}</strong>.</p>
          <p className="text-sm text-muted-foreground mb-8">Our AI screening system will review your application and our team will reach out if you're shortlisted.</p>
          <Button asChild><Link to="/careers">Browse More Opportunities</Link></Button>
        </motion.div>
      </div>
    </Layout>
  );

  return (
    <Layout>
      <Helmet><title>Apply for {job.title} | SOXIT Careers</title></Helmet>

      <section className="bg-primary pt-32 pb-12 px-6">
        <div className="max-w-3xl mx-auto">
          <Link to={`/careers/job/${jobId}`} className="inline-flex items-center gap-2 text-sm text-primary-foreground/60 hover:text-primary-foreground mb-4">
            <ArrowLeft size={16} /> Back to Job Details
          </Link>
          <h1 className="text-2xl md:text-3xl font-bold text-primary-foreground">Apply for {job.title}</h1>
          <p className="text-sm text-primary-foreground/60 mt-1">{job.department} · {job.location} · {job.job_post_id}</p>
        </div>
      </section>

      {/* Step indicator */}
      <div className="bg-surface-sunken border-b border-border py-4 px-6">
        <div className="max-w-3xl mx-auto flex gap-2">
          {steps.map((s, i) => (
            <button key={s} onClick={() => setStep(i)} className={`flex-1 text-xs font-medium py-2 px-3 rounded-md transition-colors ${i === step ? "bg-consulting-accent text-consulting-accent-foreground" : i < step ? "bg-green-500/10 text-green-600" : "bg-muted text-muted-foreground"}`}>
              {s}
            </button>
          ))}
        </div>
      </div>

      <section className="section-enterprise section-light">
        <div className="max-w-3xl mx-auto">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              {step === 0 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                  <FormField control={form.control} name="name" render={({ field }) => (
                    <FormItem><FormLabel>Full Name *</FormLabel><FormControl><Input placeholder="John Doe" {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <div className="grid md:grid-cols-2 gap-4">
                    <FormField control={form.control} name="email" render={({ field }) => (
                      <FormItem><FormLabel>Email *</FormLabel><FormControl><Input type="email" placeholder="john@example.com" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="phone" render={({ field }) => (
                      <FormItem><FormLabel>Phone *</FormLabel><FormControl><Input placeholder="+91 9876543210" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                  </div>
                  <div className="grid md:grid-cols-2 gap-4">
                    <FormField control={form.control} name="location" render={({ field }) => (
                      <FormItem><FormLabel>Location *</FormLabel><FormControl><Input placeholder="Hyderabad, India" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="work_authorization" render={({ field }) => (
                      <FormItem><FormLabel>Work Authorization *</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl><SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="Indian Citizen">Indian Citizen</SelectItem>
                            <SelectItem value="PR">Permanent Resident</SelectItem>
                            <SelectItem value="Work Visa">Work Visa</SelectItem>
                            <SelectItem value="Other">Other</SelectItem>
                          </SelectContent>
                        </Select>
                      <FormMessage /></FormItem>
                    )} />
                  </div>
                </motion.div>
              )}

              {step === 1 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                  <div className="grid md:grid-cols-2 gap-4">
                    <FormField control={form.control} name="experience" render={({ field }) => (
                      <FormItem><FormLabel>Total Experience *</FormLabel>
                        <Select onValueChange={field.onChange} value={field.value}>
                          <FormControl><SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger></FormControl>
                          <SelectContent>
                            <SelectItem value="Fresher">Fresher</SelectItem>
                            <SelectItem value="0-2 years">0-2 years</SelectItem>
                            <SelectItem value="3-5 years">3-5 years</SelectItem>
                            <SelectItem value="5-8 years">5-8 years</SelectItem>
                            <SelectItem value="8-12 years">8-12 years</SelectItem>
                            <SelectItem value="12+ years">12+ years</SelectItem>
                          </SelectContent>
                        </Select>
                      <FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="relevant_experience" render={({ field }) => (
                      <FormItem><FormLabel>Relevant Experience</FormLabel><FormControl><Input placeholder="e.g., 3 years" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                  </div>
                  <div className="grid md:grid-cols-2 gap-4">
                    <FormField control={form.control} name="current_ctc" render={({ field }) => (
                      <FormItem><FormLabel>Current CTC</FormLabel><FormControl><Input placeholder="e.g., 12 LPA" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="expected_ctc" render={({ field }) => (
                      <FormItem><FormLabel>Expected CTC</FormLabel><FormControl><Input placeholder="e.g., 18 LPA" {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                  </div>
                  <FormField control={form.control} name="notice_period" render={({ field }) => (
                    <FormItem><FormLabel>Notice Period</FormLabel><FormControl><Input placeholder="e.g., 30 days" {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <div className="grid md:grid-cols-2 gap-4">
                    <FormField control={form.control} name="linkedin_url" render={({ field }) => (
                      <FormItem><FormLabel>LinkedIn URL</FormLabel><FormControl><Input placeholder="https://linkedin.com/in/..." {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="portfolio_url" render={({ field }) => (
                      <FormItem><FormLabel>GitHub / Portfolio URL</FormLabel><FormControl><Input placeholder="https://github.com/..." {...field} /></FormControl><FormMessage /></FormItem>
                    )} />
                  </div>
                </motion.div>
              )}

              {step === 2 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
                  <FormField control={form.control} name="primary_skills" render={({ field }) => (
                    <FormItem><FormLabel>Primary Skills * (comma-separated)</FormLabel><FormControl><Textarea placeholder="React, TypeScript, Node.js, AWS..." {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="secondary_skills" render={({ field }) => (
                    <FormItem><FormLabel>Secondary Skills (comma-separated)</FormLabel><FormControl><Textarea placeholder="Docker, Kubernetes, CI/CD..." {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="certifications" render={({ field }) => (
                    <FormItem><FormLabel>Certifications (comma-separated)</FormLabel><FormControl><Input placeholder="AWS SAA, Azure AZ-900..." {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                  <FormField control={form.control} name="domain_exposure" render={({ field }) => (
                    <FormItem><FormLabel>Domain Exposure</FormLabel><FormControl><Input placeholder="BFSI, Healthcare, EdTech..." {...field} /></FormControl><FormMessage /></FormItem>
                  )} />
                </motion.div>
              )}

              {step === 3 && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6">
                  <div className="metric-card">
                    <h3 className="font-bold text-foreground mb-4">Upload Resume</h3>
                    <p className="text-sm text-muted-foreground mb-4">PDF or DOCX, max 10MB</p>
                    <label className="flex flex-col items-center justify-center border-2 border-dashed border-border rounded-lg p-8 cursor-pointer hover:border-consulting-accent transition-colors">
                      <Upload size={32} className="text-muted-foreground mb-2" />
                      <span className="text-sm text-muted-foreground">{resumeFile ? resumeFile.name : "Click to upload resume"}</span>
                      <input
                        type="file"
                        accept=".pdf,.docx"
                        className="hidden"
                        onChange={(e) => {
                          const file = e.target.files?.[0];
                          if (file && file.size > 10 * 1024 * 1024) {
                            toast({ title: "File too large", description: "Max 10MB allowed", variant: "destructive" });
                            return;
                          }
                          setResumeFile(file || null);
                        }}
                      />
                    </label>
                    {resumeFile && (
                      <div className="mt-3 flex items-center gap-2">
                        <Badge variant="outline" className="border-green-500/30 text-green-600">
                          <CheckCircle2 size={12} className="mr-1" /> {resumeFile.name}
                        </Badge>
                        <button type="button" onClick={() => setResumeFile(null)} className="text-xs text-destructive">Remove</button>
                      </div>
                    )}
                  </div>
                </motion.div>
              )}

              <div className="flex justify-between pt-6 border-t border-border">
                <Button type="button" variant="outline" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>Previous</Button>
                {step < steps.length - 1 ? (
                  <Button type="button" onClick={() => setStep(step + 1)} className="btn-consulting">Next</Button>
                ) : (
                  <Button type="submit" disabled={submitting} className="btn-consulting">
                    {submitting ? <><Loader2 size={16} className="animate-spin mr-2" />Submitting...</> : "Submit Application"}
                  </Button>
                )}
              </div>
            </form>
          </Form>
        </div>
      </section>
    </Layout>
  );
};

export default JobApplication;
